[package]
name = "search-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
scraper = "0.14"
regex = "1.12.3"
once_cell = "1.21.3"
futures = "0.3"